one:
	python test_challenges.py TestChallenge.test_challenge_one
two:
	python test_challenges.py TestChallenge.test_challenge_two
three:
	python test_challenges.py TestChallenge.test_challenge_three	
