one:
	mkdir -p ../challenge/one/
	cp ../src/challenge_one.py ../challenge/one/
	python -B test_challenge_one.py TestChallenge.test
two:
	mkdir -p ../challenge/two/
	cp ../src/challenge_two.py ../challenge/two/
	python -B test_challenge_two.py TestChallenge.test
three:
	mkdir -p ../challenge/three/
	cp ../src/challenge_three.py ../challenge/three/
	python -B test_challenge_three.py TestChallenge.test	
