one:
	python -B test_challenges.py TestChallenge.test_challenge_one
two:
	python -B test_challenges.py TestChallenge.test_challenge_two
three:
	python -B test_challenges.py TestChallenge.test_challenge_three	
